  version: '3'
  services:
    mosquitto:
      container_name: mosquitto
      image: eclipse-mosquitto
      volumes:
        - ./config/:/mosquitto/config/
        - ./data/:/mosquitto/data
        - ./log/:/mosquitto/log/
      network_mode: host
